import React, { Component, useState, useEffect } from "react";
import Axios from "axios";

const SqlTest = () => {
  const [testQueryData, setTestQueryData] = useState([]);
  const TestQuery = () => {
    Axios.post("http://localhost:3001/api/query/test")
      .then((response) => {
        console.log(response.data);
        setTestQueryData(response.data);
      })
      .catch((error) => {
        console.log(error);
      });
  };

  const data = () => {
    Object.entries(testQueryData).map((key, val) => {
      return <p>{key}</p>;
    });
  };
  return (
    <div>
      <h1>THIS PAGE IS FOR SQL TESTING ONLY. DO NOT EDIT THIS FILE.</h1>
      <button onClick={TestQuery}>Run Query</button>
    </div>
  );
};

export default SqlTest;
